modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Jammies/issues"
license="MIT"

[[mods]]
modId="jammies"
version="${file.jarVersion}"
displayName="Jammies"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jammies"
authors="Mrbysco, ShyNieke"
credits="Buuz135 for making Cat Jammies"
description='''
Making zombies dance since 2023
'''

[[dependencies.jammies]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="jammies.mixins.json"